name: my_wallet
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  circular_bottom_navigation: ^1.0.1
  flutter_svg: ^0.14.0
  cached_network_image: ^2.0.0
  shimmer: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Playfair
      fonts:
        - asset: assets/fonts/playfair/Regular.ttf
          weight: 400
        - asset: assets/fonts/playfair/Medium.ttf
          weight: 500
        - asset: assets/fonts/playfair/SemiBold.ttf
          weight: 600
        - asset: assets/fonts/playfair/Bold.ttf
          weight: 700
        - asset: assets/fonts/playfair/Black.ttf
          weight: 800